apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: trippass-front-nodeport
spec:
  selector:
    matchLabels:
      app: trippass-front-nodeport
  template:
    metadata:
      labels:
        app: trippass-front-nodeport
    spec:
      containers:
      - name: trippass-front
        image: dockerId/imageName:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            secretKeyRef:
              name: trippass-secrets
              key: REACT_APP_API_URL
        - name: REACT_APP_KAKAO_REDIRECT_URI
          valueFrom:
            secretKeyRef:
              name: trippass-secrets
              key: REACT_APP_KAKAO_REDIRECT_URI
        - name: REACT_APP_KAKAO_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: trippass-secrets
              key: REACT_APP_KAKAO_CLIENT_ID
      nodeSelector:
        kubernetes.io/hostname: instance name
---
apiVersion: v1
kind: Service
metadata:
  name: trippass-front-service
spec:
  type: NodePort
  selector:
    app: trippass-front-nodeport
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 80 
      nodePort: 30800
